// Writes test vectors from the web app's theory engine for the plugin's C++ port
// (plugin/tests/CoreTests.cpp compares its results with these, line by line).
// Run with: npm run gen:plugin            (writes the committed subset)
//           VECTORS_FULL=1 VECTORS_OUT=/tmp/v.txt npm run gen:plugin   (every note set)
import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { analyzeArpeggio, exactArpeggios, suggestArpeggios } from '../src/theory/arpeggios';
import { parseArpeggioInput } from '../src/theory/arpInput';
import { parseArrangementText } from '../src/theory/arrangement';
import { CHORD_TYPES, chordPcs } from '../src/theory/chords';
import { identifyChord } from '../src/theory/identify';
import { parseChordSymbol } from '../src/theory/parse';

const full = !!process.env.VECTORS_FULL;
const outPath = process.env.VECTORS_OUT ?? 'plugin/tests/vectors.txt';
const ROOT_NAMES = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B'];

it('generates plugin test vectors', () => {
  const lines: string[] = ['# GENERATED by scripts/plugin-vectors.gen.ts — expected results from the web app'];
  const mask = (pcs: number[]) => pcs.reduce((m, p) => m | (1 << p), 0);

  // Identification: every set of 2+ pitch classes (a deterministic sample unless full), each note in the bass.
  const names = new Set<string>();
  let n = 0;
  for (let set = 1; set < 4096; set++) {
    const pcs = [...Array(12).keys()].filter((p) => set & (1 << p));
    if (pcs.length < 2) continue;
    for (let b = 0; b < pcs.length; b++) {
      n++;
      const order = [...pcs.slice(b), ...pcs.slice(0, b)];
      const midis: number[] = [];
      for (const pc of order) {
        let m = midis.length ? midis[midis.length - 1] + 1 : 40 + ((pc - 4 + 12) % 12);
        while (((m % 12) + 12) % 12 !== pc) m++;
        midis.push(m);
      }
      const matches = identifyChord(midis);
      for (const m of matches) names.add(m.name);
      if (!full && n % 23 !== 0) continue;
      lines.push(`I\t${midis.join(' ')}\t${matches.slice(0, 3).map((m) => m.name).join('\t')}`);
    }
  }

  // Parsing: every identified name must parse back; plus hand-written symbols.
  const symbols = [
    ...[...names].filter((_, i) => full || i % 37 === 0),
    'Am7', 'C#m7b5', 'Bbmaj7/D', 'G7(#9)', 'F6/9', 'Eø', 'D-7', 'Eb(add#11,no3)', 'C7(b9,#11)', 'G7sus4(b9)', 'C9(b5)', 'Cmaj7(no3)',
    'Dm(add b6)', 'C(omit3)', 'CΔ7', 'C°7', 'Cmaj7#11', 'C13', 'Cm11', 'Bb7alt', 'E7#9', 'Fmaj9', 'Gsus', 'A5', 'Cadd9', 'C2', 'Csus24',
    'Cm(maj7)', 'CmM7', 'C+', 'C+7', 'Caug7', 'C7+5', 'C7-9', 'Cmi7', 'Cmin7', 'CMA7', 'CM7', 'C/E', 'D/F#', 'Ab/C', 'E♭7♯9', 'Fx', 'Cbb',
    'Xyz', 'C(add13)', 'Cm6/9', 'C7(no5)', 'Gm7/C', 'Bbm(add9)/Db',
  ];
  for (const s of symbols) {
    const c = parseChordSymbol(s);
    lines.push(c ? `P\t${s}\t${c.display}\t${mask(chordPcs(c))}\t${c.rootPc}\t${c.bassPc ?? -1}` : `P\t${s}\t!`);
  }

  // Arpeggios: own + reductions + suggestions with fit, for chord types on several roots.
  const roots = full ? [...Array(12).keys()] : [0, 3, 6];
  for (const t of CHORD_TYPES) {
    if (t.parseOnly) continue;
    for (const r of roots) {
      const sym = ROOT_NAMES[r] + (t.id === 'maj' ? '' : t.aliases[0] ?? t.id);
      const c = parseChordSymbol(sym);
      if (!c) continue;
      const ex = exactArpeggios(c).map((a) => a.name);
      lines.push(`E\t${sym}\t${ex.join('\t')}`);
      const subs = suggestArpeggios(c, { limit: 20 }).map((a) => `${a.name}=${a.fit.toFixed(4)}=${a.sound ?? ''}=${a.notes.map((x) => x.name).join(' ')}`);
      lines.push(`S\t${sym}\t${subs.join('\t')}`);
    }
  }

  // Typed arpeggios (chord symbol or notes) analysed over a chord.
  const typed: [string, string][] = [
    ['Cmaj7', 'Em7'], ['Cmaj7', 'E G B D'], ['Am7', 'C E G B'], ['G7', 'Bdim'], ['G7', 'Abmaj7'], ['Dm7', 'F A C E'], ['Eb', 'Eb(add#11,no3)'],
    ['E7', 'G#dim7'], ['C', 'F# A# C#'], ['Bbmaj7', 'D F A'], ['F#m7b5', 'A C E'], ['C7', 'Gb Bb Db'], ['Am', 'Bb D F'], ['Cmaj7', 'xyz'],
    ['Cmaj7', 'Bb-D-F-A'], ['Dm7', 'E G Bb D'],
  ];
  for (const [chord, arp] of typed) {
    const c = parseChordSymbol(chord)!;
    const r = parseArpeggioInput(arp);
    if ('error' in r) {
      lines.push(`A\t${chord}\t${arp}\t!`);
      continue;
    }
    const a = analyzeArpeggio(c, r.chord);
    lines.push(`A\t${chord}\t${arp}\t${r.name}\t${r.recognisedFrom ?? ''}\t${a.fit.toFixed(4)}\t${a.sound ?? ''}\t${a.description}\t${a.warning ?? ''}`);
  }

  // Arrangement files.
  const files = [
    'FRETBOARD LAB\nKey: A minor\n\n[data]\n# comment\ntuning: D2 A2 D3 G3 B3 E4\ntempo: 90\nposition: 5-9\nchord: Dm7 | arpeggio: Fmaj9 | position: 0-4 | length: 4\nchord: G7 | arpeggio: - | position: all | length: 2\nchord: Cmaj7 | arpeggio: E G B D | position: neck | length: 8\n',
    'Dm7 -> Fmaj7\nG7 => Bdim\nCmaj7 -> -\n',
    'Am F C G\n',
    'Dm7 | G7 | Cmaj7(no3) Eb(add#11, no3)\n',
    '[data]\nchord: Am | position: frets 3-7 | length: 2 bars\nchord: E7 | length: half\nchord: X | position: nowhere | length: lots\ntempo: 500\n',
  ];
  for (const f of files) {
    const { doc, errors } = parseArrangementText(f);
    const slots = doc.chords.map((c, i) => {
      const s = doc.slots[i];
      const pos = s.pos === 'global' || s.pos === 'neck' ? s.pos : `${s.pos.start}-${s.pos.end}`;
      return `${c}~${s.arp ?? '-'}~${pos}~${s.beats}`;
    });
    const pos = doc.position === undefined ? 'unset' : doc.position === null ? 'neck' : `${doc.position.start}-${doc.position.end}`;
    lines.push(`F\t${JSON.stringify(f)}\t${doc.tempo ?? 0}\t${pos}\t${(doc.tuning ?? []).join(' ')}\t${errors.length}\t${slots.join('\t')}`);
  }
  writeFileSync(outPath, lines.join('\n') + '\n');
});
