// Writes plugin/Source/core/GeneratedTables.inc from the web app's chord dictionary, scales and
// tunings, so the VST plugin names, parses and rates chords exactly like the web app.
// Run with: npm run gen:plugin
import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { CHORD_TYPES } from '../src/theory/chords';
import { SCALES } from '../src/theory/scales';
import { TUNINGS } from '../src/theory/tunings';

const q = (s: string) => JSON.stringify(s); // valid C++ string literal for our (UTF-8) content
const list = (xs: string[]) => `{${xs.map(q).join(', ')}}`;

it('generates plugin tables', () => {
  const chords = CHORD_TYPES.map(
    (t) =>
      `  {${q(t.id)}, ${q(t.symbol)}, ${q(t.name)}, ${list(t.degrees)}, ${list(t.optional)}, ${t.prior}, ${list(t.aliases)}, ${t.parseOnly ? 'true' : 'false'}, ${q(t.family)}, ${list(t.scales)}},`,
  );
  const scales = SCALES.map((s) => `  {${q(s.id)}, ${q(s.name)}, ${list(s.degrees)}, ${s.prior}},`);
  const tunings = TUNINGS.map((t) => `  {${q(t.id)}, ${q(t.name)}, ${q(t.group)}, {${t.strings.join(', ')}}},`);
  const out = `// GENERATED by scripts/plugin-tables.gen.ts from src/theory/{chords,scales,tunings}.ts.
// Do not edit by hand — run \`npm run gen:plugin\` after changing the web app's dictionary.

static const std::vector<ChordDef> kChordDefs = {
${chords.join('\n')}
};

static const std::vector<ScaleDef> kScaleDefs = {
${scales.join('\n')}
};

static const std::vector<TuningDef> kTuningDefs = {
${tunings.join('\n')}
};
`;
  writeFileSync('plugin/Source/core/GeneratedTables.inc', out);
});
